-- Transactionally applied by LocalRepository after making a pre-migration backup.
CREATE TABLE books (id text PRIMARY KEY NOT NULL, sha256 text NOT NULL UNIQUE, title text NOT NULL, author text NOT NULL, language text DEFAULT 'en' NOT NULL, description text DEFAULT '' NOT NULL, original_relative_path text NOT NULL, status text NOT NULL, processing_progress integer DEFAULT 0 NOT NULL, processing_error text, created_at text NOT NULL, updated_at text NOT NULL);
CREATE TABLE chapters (id text PRIMARY KEY NOT NULL, book_id text NOT NULL REFERENCES books(id) ON DELETE CASCADE, spine_index integer NOT NULL, href text NOT NULL, title text NOT NULL, start_block_index integer NOT NULL, end_block_index integer NOT NULL, UNIQUE(book_id, spine_index));
CREATE TABLE book_blocks (id text PRIMARY KEY NOT NULL, book_id text NOT NULL REFERENCES books(id) ON DELETE CASCADE, chapter_id text NOT NULL REFERENCES chapters(id) ON DELETE CASCADE, spine_index integer NOT NULL, block_index integer NOT NULL, block_type text NOT NULL, heading_path text NOT NULL, text text NOT NULL, locator text NOT NULL, UNIQUE(book_id, spine_index, block_index));
CREATE TABLE book_chunks (id text PRIMARY KEY NOT NULL, book_id text NOT NULL REFERENCES books(id) ON DELETE CASCADE, chapter_id text NOT NULL REFERENCES chapters(id) ON DELETE CASCADE, ordinal integer NOT NULL, spine_index integer NOT NULL, start_block_index integer NOT NULL, end_block_index integer NOT NULL, heading_path text NOT NULL, text text NOT NULL, normalized_text text NOT NULL, locator_start text NOT NULL, locator_end text NOT NULL, token_count integer NOT NULL, UNIQUE(book_id, ordinal));
CREATE INDEX chunks_scope_idx ON book_chunks(book_id, spine_index, end_block_index);
CREATE VIRTUAL TABLE chunks_fts USING fts5(chunk_id UNINDEXED, book_id UNINDEXED, heading, text, tokenize='unicode61 remove_diacritics 2');
CREATE TABLE reading_progress (book_id text PRIMARY KEY NOT NULL REFERENCES books(id) ON DELETE CASCADE, locator text NOT NULL, spine_index integer NOT NULL, block_index integer NOT NULL, percentage real NOT NULL, settings text, updated_at text NOT NULL);
CREATE TABLE highlights (id text PRIMARY KEY NOT NULL, book_id text NOT NULL REFERENCES books(id) ON DELETE CASCADE, exact text NOT NULL, prefix text NOT NULL, suffix text NOT NULL, color text NOT NULL, locator text NOT NULL, note text, created_at text NOT NULL, updated_at text NOT NULL);
CREATE TABLE threads (id text PRIMARY KEY NOT NULL, book_id text NOT NULL REFERENCES books(id) ON DELETE CASCADE, title text NOT NULL, created_at text NOT NULL, updated_at text NOT NULL);
CREATE TABLE messages (id text PRIMARY KEY NOT NULL, thread_id text NOT NULL REFERENCES threads(id) ON DELETE CASCADE, role text NOT NULL, text text NOT NULL, action text, scope text, citations text NOT NULL, created_at text NOT NULL);
CREATE TABLE ai_usage (id text PRIMARY KEY NOT NULL, book_id text NOT NULL REFERENCES books(id) ON DELETE CASCADE, model text NOT NULL, action text NOT NULL, input_tokens integer, output_tokens integer, latency_ms integer NOT NULL, created_at text NOT NULL);
CREATE TABLE settings (key text PRIMARY KEY NOT NULL, value text NOT NULL, updated_at text NOT NULL);
