import { useEffect, useState } from "react";
import { ArrowLeft, Braces, FileText, Highlighter, Quote, Trash2 } from "lucide-react";
import type { Highlight, LocalBook } from "@/shared/ipc";
import { Link } from "@/renderer/router";

export function WorkspaceView({ book }: { book: LocalBook }) {
  const [highlights, setHighlights] = useState<Highlight[]>([]);
  useEffect(() => { void window.marginReader.highlights.list(book.id).then(setHighlights); }, [book.id]);
  async function remove(id: string) { await window.marginReader.highlights.delete(id); setHighlights((items) => items.filter((item) => item.id !== id)); }
  return <main className="min-h-dvh bg-[#f4efe5] px-8 pb-20 pt-[52px]"><header className="mx-auto flex h-16 max-w-6xl items-center justify-between border-b border-[#d8d0c2]"><Link href={`/reader/${book.id}`} className="flex items-center gap-2 text-sm"><ArrowLeft size={16}/> Back to book</Link><div className="flex gap-2"><button onClick={() => void window.marginReader.notes.export(book.id, "markdown")} className="flex items-center gap-2 rounded-full border border-[#ccc3b6] px-4 py-2 text-xs"><FileText size={14}/> Markdown</button><button onClick={() => void window.marginReader.notes.export(book.id, "json")} className="flex items-center gap-2 rounded-full border border-[#ccc3b6] px-4 py-2 text-xs"><Braces size={14}/> JSON</button></div></header><div className="mx-auto max-w-6xl pt-12"><p className="small-caps text-xs text-[#7d756b]">Reader notebook</p><h1 className="mt-3 reader-serif text-4xl">{book.title}</h1><p className="mt-2 text-sm text-[#777067]">{book.author} · {highlights.length} saved passage{highlights.length === 1 ? "" : "s"}</p><div className="mt-10 grid gap-8 lg:grid-cols-[220px_1fr]"><nav className="space-y-1"><div className="flex items-center gap-2 rounded-lg bg-white/50 px-3 py-2 text-sm font-medium"><Highlighter size={15}/>Highlights <span className="ml-auto text-xs text-[#8b8378]">{highlights.length}</span></div><div className="flex items-center gap-2 px-3 py-2 text-sm text-[#7b746b]"><Quote size={15}/>AI questions</div></nav><section><h2 className="text-xs font-semibold uppercase tracking-[.15em] text-[#797168]">Highlights & notes</h2>{!highlights.length ? <div className="mt-5 rounded-2xl border border-dashed border-[#cfc6b9] p-12 text-center"><Highlighter className="mx-auto mb-3 text-[#90887d]"/><p className="reader-serif text-xl">Your margins are still quiet.</p><p className="mt-2 text-xs text-[#777067]">Select a passage in the reader to save it here.</p></div> : <div className="mt-5 space-y-4">{highlights.map((item) => <article key={item.id} className="rounded-2xl border border-[#d7cfc3] bg-white/35 p-6"><blockquote className="border-l-2 border-[#d4aa51] pl-4 reader-serif text-lg leading-relaxed">“{item.exact}”</blockquote>{item.note && <p className="mt-4 text-sm text-[#5f5951]">{item.note}</p>}<div className="mt-5 flex justify-between"><Link href={`/reader/${book.id}`} className="text-xs font-medium text-[#4c6279]">Open in book</Link><button onClick={() => void remove(item.id)} aria-label="Delete highlight" className="text-[#877e73] hover:text-red-700"><Trash2 size={15}/></button></div></article>)}</div>}</section></div></div></main>;
}
