"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, Braces, FileText, Highlighter, Quote, Trash2 } from "lucide-react";
import type { PublicationLocator } from "@/lib/reader/publication-adapter";

type Highlight = { id: string; exact: string; locator: PublicationLocator; color: string; note?: string; createdAt: string };
export function WorkspaceView({ book }: { book: { id: string; title: string; author: string } }) {
  const [highlights, setHighlights] = useState<Highlight[]>(() => { if (typeof window === "undefined") return []; const saved = localStorage.getItem(`margin-reader:highlights:${book.id}`); if (!saved) return []; try { return JSON.parse(saved) as Highlight[]; } catch { return []; } });
  function remove(id: string) { const next = highlights.filter((item) => item.id !== id); setHighlights(next); localStorage.setItem(`margin-reader:highlights:${book.id}`, JSON.stringify(next)); void fetch(`/api/books/${book.id}/highlights?id=${encodeURIComponent(id)}`, { method: "DELETE" }); }
  function download(format: "md" | "json") {
    const content = format === "json" ? JSON.stringify({ book: { title: book.title, author: book.author }, highlights }, null, 2) : `# ${book.title}\n\n${highlights.map((item) => `> ${item.exact}\n\n${item.note ? `**Note:** ${item.note}\n\n` : ""}`).join("---\n\n")}`;
    const url = URL.createObjectURL(new Blob([content], { type: format === "json" ? "application/json" : "text/markdown" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${book.title.replace(/\W+/g, "-").toLowerCase()}-notes.${format}`; anchor.click(); URL.revokeObjectURL(url);
  }
  return <main className="min-h-screen px-5 pb-20 sm:px-10 lg:px-16"><header className="mx-auto flex h-20 max-w-6xl items-center justify-between border-b border-[#d8d0c2]"><Link href={`/reader/${book.id}`} className="flex items-center gap-2 text-sm"><ArrowLeft size={16}/> Back to book</Link><div className="flex gap-2"><button onClick={() => download("md")} className="flex items-center gap-2 rounded-full border border-[#ccc3b6] px-4 py-2 text-xs"><FileText size={14}/> Markdown</button><button onClick={() => download("json")} className="flex items-center gap-2 rounded-full border border-[#ccc3b6] px-4 py-2 text-xs"><Braces size={14}/> JSON</button></div></header><div className="mx-auto max-w-6xl pt-12"><p className="small-caps text-xs text-[#7d756b]">Reader notebook</p><h1 className="mt-3 reader-serif text-4xl">{book.title}</h1><p className="mt-2 text-sm text-[#777067]">{book.author} · {highlights.length} saved passage{highlights.length === 1 ? "" : "s"}</p><div className="mt-10 grid gap-8 lg:grid-cols-[220px_1fr]"><nav className="space-y-1"><div className="flex items-center gap-2 rounded-lg bg-white/50 px-3 py-2 text-sm font-medium"><Highlighter size={15}/>Highlights <span className="ml-auto text-xs text-[#8b8378]">{highlights.length}</span></div><div className="flex items-center gap-2 px-3 py-2 text-sm text-[#7b746b]"><Quote size={15}/>AI questions <span className="ml-auto text-xs">0</span></div></nav><section><h2 className="text-xs font-semibold uppercase tracking-[.15em] text-[#797168]">Highlights & notes</h2>{!highlights.length ? <div className="mt-5 rounded-2xl border border-dashed border-[#cfc6b9] p-12 text-center"><Highlighter className="mx-auto mb-3 text-[#90887d]"/><p className="reader-serif text-xl">Your margins are still quiet.</p><p className="mt-2 text-xs text-[#777067]">Select a passage in the reader to save it here.</p></div> : <div className="mt-5 space-y-4">{highlights.map((item) => <article key={item.id} className="rounded-2xl border border-[#d7cfc3] bg-white/35 p-6"><blockquote className="border-l-2 border-[#d4aa51] pl-4 reader-serif text-lg leading-relaxed">“{item.exact}”</blockquote>{item.note && <p className="mt-4 text-sm text-[#5f5951]">{item.note}</p>}<div className="mt-5 flex justify-between"><Link href={`/reader/${book.id}?locator=${encodeURIComponent(JSON.stringify(item.locator))}`} className="text-xs font-medium text-[#4c6279]">Open in book</Link><button onClick={() => remove(item.id)} aria-label="Delete highlight" className="text-[#877e73] hover:text-red-700"><Trash2 size={15}/></button></div></article>)}</div>}</section></div></div></main>;
}
