import { NextResponse } from "next/server";
import { randomUUID } from "node:crypto";
import { z } from "zod";
import { getSessionId } from "@/lib/auth/session";
import { ownsBook, serverRepository } from "@/lib/books/server-repository";

const schema = z.object({ id: z.string().uuid().optional(), exact: z.string().min(1).max(20_000), prefix: z.string().max(500).default(""), suffix: z.string().max(500).default(""), color: z.enum(["ochre", "sage", "blue", "rose"]).default("ochre"), locator: z.record(z.string(), z.unknown()), note: z.string().max(10_000).optional() });
export async function GET(_request: Request, { params }: { params: Promise<{ bookId: string }> }) { const { bookId } = await params; const ownerId = await getSessionId(); if (!ownsBook(ownerId, bookId)) return NextResponse.json({ error: "Not found" }, { status: 404 }); return NextResponse.json({ highlights: [...serverRepository.highlights.values()].filter((item) => item.ownerId === ownerId && item.bookId === bookId) }); }
export async function POST(request: Request, { params }: { params: Promise<{ bookId: string }> }) { const { bookId } = await params; const ownerId = await getSessionId(); if (!ownsBook(ownerId, bookId)) return NextResponse.json({ error: "Not found" }, { status: 404 }); const parsed = schema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "Invalid highlight." }, { status: 400 }); const now = new Date().toISOString(); const item = { ...parsed.data, id: parsed.data.id ?? randomUUID(), ownerId, bookId, locator: parsed.data.locator as never, createdAt: now, updatedAt: now }; serverRepository.highlights.set(item.id, item); return NextResponse.json({ highlight: item }, { status: 201 }); }
export async function DELETE(request: Request, { params }: { params: Promise<{ bookId: string }> }) { const { bookId } = await params; const ownerId = await getSessionId(); const id = new URL(request.url).searchParams.get("id"); const item = id ? serverRepository.highlights.get(id) : undefined; if (!item || item.ownerId !== ownerId || item.bookId !== bookId) return NextResponse.json({ error: "Not found" }, { status: 404 }); serverRepository.highlights.delete(item.id); return new NextResponse(null, { status: 204 }); }
